CREATE SEQUENCE S_SCREENING_ID START WITH 1 INCREMENT BY 50;
CREATE TABLE T_SCREENINGS
(
    SCREENING_ID NUMERIC PRIMARY KEY,
    SCREENING_ROOM_ID  NUMERIC(10,0) CONSTRAINT FK_SCREENING_ROOM REFERENCES T_ROOMS(ROOM_ID),
    SCREENING_TITLE VARCHAR(40),
    SCREENING_START_HOUR TIMESTAMP
)