CREATE SEQUENCE S_RESERVATION_ID START WITH 1 INCREMENT BY 50;
CREATE TABLE T_RESERVATIONS(
    RESERVATION_ID NUMERIC(10,0) PRIMARY KEY,
    RESERVATION_NAME VARCHAR(20),
    RESERVATION_SURNAME VARCHAR(40),
    RESERVATION_CREATION_DATE TIMESTAMP,
    RESERVATION_SCREENING_ID NUMERIC(10,0) CONSTRAINT FK_RESERVATION_SCREENING REFERENCES T_SCREENINGS(SCREENING_ID)

)