CREATE SEQUENCE S_SEAT_ID START WITH 1 INCREMENT BY 50;
CREATE TABLE T_SEATS(
    SEAT_ID NUMERIC(10,0) PRIMARY KEY,
    SEAT_ROOM_ID NUMERIC(10,0) CONSTRAINT FK_SEAT_ROOM REFERENCES T_ROOMS(ROOM_ID),
    SEAT_ROW_NUMBER NUMERIC(2,0),
    SEAT_COLUMN_NUMBER NUMERIC(2,0)
)