CREATE SEQUENCE S_TICKET_ID START WITH 1 INCREMENT BY 50;
CREATE TABLE T_TICKETS
(
    TICKET_ID             NUMERIC(10, 0) PRIMARY KEY,
    TICKET_RESERVATION_ID NUMERIC(10, 0)
        CONSTRAINT FK_TICKET_RESERVATION REFERENCES T_RESERVATIONS (RESERVATION_ID),
    TICKET_SEAT_ID        NUMERIC(10, 0)
        CONSTRAINT FK_TICKET_SEAT REFERENCES T_SEATS (SEAT_ID),
    TICKET_TICKET_TYPE_ID NUMERIC(10, 0)
        CONSTRAINT FK_TICKET_TICKET_TYPE REFERENCES T_TICKET_TYPES (TICKET_TYPE_ID)
);
COMMENT ON COLUMN T_TICKETS.TICKET_ID IS 'TICKET ID , SEQUENCE S_TICKET_ID';

COMMENT ON COLUMN T_TICKETS.TICKET_RESERVATION_ID IS 'RESERVATION CONNECTED WITH TICKET';

COMMENT ON COLUMN T_TICKETS.TICKET_SEAT_ID IS 'SEAT FOR GIVEN TICKET';

COMMENT ON COLUMN T_TICKETS.TICKET_TICKET_TYPE_ID IS 'TICKET TYPE';
