CREATE SEQUENCE S_TICKET_TYPE_ID START WITH 1 INCREMENT BY 50;
CREATE TABLE T_TICKET_TYPES(
        TICKET_TYPE_ID NUMERIC(10,0) PRIMARY KEY,
        TICKET_TYPE_CODE VARCHAR(2),
        TICKET_TYPE_NAME VARCHAR(30),
        TICKET_TYPE_PRICE NUMERIC(4,2)
)