INSERT INTO T_ROOMS VALUES (NEXTVAL('S_ROOM_ID'),'1');
INSERT INTO T_ROOMS VALUES (NEXTVAL('S_ROOM_ID'),'2');
INSERT INTO T_ROOMS VALUES (NEXTVAL('S_ROOM_ID'),'3');
INSERT INTO T_ROOMS VALUES (NEXTVAL('S_ROOM_ID'),'4');

COMMIT;

INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),1,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),1,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),1,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),1,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),1,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),1,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),1,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),2,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),2,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),2,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),2,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),2,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),2,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),2,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),3,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),3,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),3,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),3,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),3,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),3,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),3,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),4,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),4,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),4,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),4,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),4,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),4,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),4,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),1,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),1,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),1,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),1,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),1,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),1,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),1,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),2,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),2,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),2,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),2,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),2,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),2,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),2,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),3,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),3,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),3,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),3,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),3,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),3,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),3,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),4,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),4,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),4,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),4,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),4,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),4,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),4,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),1,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),1,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),1,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),1,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),1,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),1,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),1,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),2,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),2,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),2,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),2,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),2,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),2,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),2,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),3,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),3,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),3,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),3,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),3,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),3,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),3,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),4,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),4,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),4,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),4,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),4,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),4,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),4,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),1,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),1,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),1,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),1,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),1,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),1,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),1,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),2,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),2,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),2,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),2,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),2,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),2,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),2,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),3,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),3,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),3,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),3,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),3,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),3,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),3,7);


INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),4,1);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),4,2);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),4,3);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),4,4);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),4,5);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),4,6);
INSERT INTO T_SEATS VALUES (NEXTVAL('S_SEAT_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),4,7);

COMMIT;

INSERT INTO T_TICKET_TYPES VALUES(NEXTVAL('S_TICKET_TYPE_ID'),'A','ADULT',25.00);
INSERT INTO T_TICKET_TYPES VALUES(NEXTVAL('S_TICKET_TYPE_ID'),'S','STUDENT',18.00);
INSERT INTO T_TICKET_TYPES VALUES(NEXTVAL('S_TICKET_TYPE_ID'),'C','CHILD',12.50);

COMMIT;

INSERT INTO T_SCREENINGS VALUES(NEXTVAL('S_SCREENING_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),'LA TIGRA E LA NEVE',to_date('2020-02-20-10-20','YYYY-MM-DD-hh-MI'));
INSERT INTO T_SCREENINGS VALUES(NEXTVAL('S_SCREENING_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='2'),'BATOMAN',to_date('2020-02-20-12-20','YYYY-MM-DD-hh-MI'));
INSERT INTO T_SCREENINGS VALUES(NEXTVAL('S_SCREENING_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='3'),'RWBY',to_date('2020-02-20-09-20','YYYY-MM-DD-hh-MI'));
INSERT INTO T_SCREENINGS VALUES(NEXTVAL('S_SCREENING_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='4'),'TEST1',to_date('2020-02-20-11-20','YYYY-MM-DD-hh-MI'));
INSERT INTO T_SCREENINGS VALUES(NEXTVAL('S_SCREENING_ID'),(SELECT ROOM_ID FROM T_ROOMS WHERE ROOM_NUMBER='1'),'TEST2',to_date('2020-02-20-12-20','YYYY-MM-DD-hh-MI'));

COMMIT;